name: pixel-pirates-backend
region: nyc

services:
  - name: api
    dockerfile_path: Dockerfile.prod
    github:
      branch: main
      deploy_on_push: true
      repo: your-username/pixel-pirates-backend
    health_check:
      http_path: /api/v1/health
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: DEBUG
        value: "False"
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_HOST
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_FACT_CHECK_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: NEWS_API_KEY
        scope: RUN_TIME
        type: SECRET

databases:
  - name: pixelpirates-db
    engine: PG
    production: true
    version: "15"

  - name: pixelpirates-redis
    engine: REDIS
    production: true
    version: "7"
